{{- $chartName := include "raster-catalog-manager.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracingUrl := include "raster-catalog-manager.tracingUrl" . -}}
{{- $metricsUrl := include "raster-catalog-manager.metricsUrl" . -}}
{{- $db := (include "common.db.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  DB_HOST: {{ $db.host }}
  DB_PORT:  {{ $db.port | quote }}
  DB_NAME: {{ $db.name }}
  DB_USE_SSL: {{ $db.sslEnabled | quote }}
  DB_SCHEMA: {{ $db.schema }}
  DB_LOGGING: {{ $db.logging | quote }}
  PGAPPNAME: {{ $chartName }}
{{- end }}
