{{- $chartName := include "raster-catalog-manager.name" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $tracingUrl := include "raster-catalog-manager.tracingUrl" . -}}
{{- $metricsUrl := include "raster-catalog-manager.metricsUrl" . -}}
{{- $tracingEnabled := include "raster-catalog-manager.tracingEnabled" . -}}
{{- $metricsEnabled := include "raster-catalog-manager.metricsEnabled" . -}}
{{- $metricsBuckets := include "raster-catalog-manager.metricsBuckets" . -}}
{{- $db := (include "common.db.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  {{ if $tracingEnabled }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  {{ if $metricsEnabled }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ $metricsBuckets | toJson | quote }}
  {{ end }}
  DB_HOST: {{ $db.host }}
  DB_PORT:  {{ $db.port | quote }}
  DB_NAME: {{ $db.name }}
  DB_SSL_ENABLE: {{ $db.sslEnabled | quote }}
  DB_SSL_CA: {{ .Values.db.caFile | quote}}
  DB_SSL_KEY: {{ .Values.db.caKey | quote}}
  DB_SSL_CERT: {{ .Values.db.certFile | quote}}
  DB_SCHEMA: {{ $db.schema }}
  DB_LOGGING: {{ $db.logging | quote }}
  PGAPPNAME: {{ $chartName }}
{{- end }}
