global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ""
  db:
    host: ""
    name: ""
    port: 5432
    sslEnabled: false
    schema: ""
    secrets:
      useExternal: false
      externalSecretName: ''
  ca:
    secretName: ''
    path: '/usr/local/share/ca-certificates'
    key: 'ca.crt'
  ingress:
    domain: 'apps.aroapp.io'    

db:
  host: ""
  name: ""
  port: 5432
  sslEnabled: false
  sslMountPath: /mnt/db/certs
  caFile: "caFile"
  caKey: "keyFile"
  certFile: "certFile"
  schema: "RasterCatalogManager"
  logging: false
  secrets:
    useExternal: false
    externalSecretName: ''

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30019 #for minikube deployment only
resetOnConfigChange: true

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

image:
  repository: raster-catalog-manager
  # If commented, appVersion will be taken. See: _helpers.tpl
  # tag: 'latest'

# add pod annotations
# example:
# podAnnotations:
  # annotation1: annotation-value-1
  # annotation2: annotation-value-2
podAnnotations: {}

env:
  port: 80
  targetPort: 8080
  protocol: TCP
  logLevel: warn
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/traces
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

resources:
  enabled: false
  value:
    limits:
      cpu: 0.8
      memory: 512Mi
    requests:
      cpu: 0.2
      memory: 512Mi

route:
  enabled: false
  path: /
  https: true
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)

ingress:
  enabled: false
  type: 'nginx-org' # supported values: 'nginx-org' | 'nginx-kubernetes'
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'

local: # for local stand alone deployment, external secrets should be used for full deployment  
  db:
    createSecret: false
    userName: postgres
    password: postgres
    certs:
      ca: certs/ca.pem
      key: certs/key.pem
      cert: certs/cert.pem
